name: test

on:
  push:
    branches:
      - main

jobs:
  nondeterminism:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - run: ./install_colpack.sh
      - run: ./run_colpack.sh