name: test

on:
  push:
    branches:
      - main

jobs:
  nondeterminism:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Make the script files executable
        run: chmod +x install_colpack.sh run_colpack.sh
      - name: Install ColPack
        run: ./install_colpack.sh
      - name: Run ColPack
        run: ./run_colpack.sh